if(NOT ANDROID)
    return()
endif()

if(NOT DEFINED GEMRB_ANDROID_SDL2_ROOT OR NOT EXISTS "${GEMRB_ANDROID_SDL2_ROOT}/CMakeLists.txt")
    message(FATAL_ERROR "GEMRB_ANDROID_SDL2_ROOT must point to the prepared SDL2 source tree")
endif()

set(SDL_SHARED ON CACHE BOOL "" FORCE)
set(SDL_STATIC OFF CACHE BOOL "" FORCE)
set(SDL_TEST OFF CACHE BOOL "" FORCE)
set(SDL_TESTS OFF CACHE BOOL "" FORCE)
set(SDL_INSTALL OFF CACHE BOOL "" FORCE)
set(SDL2_DISABLE_UNINSTALL ON CACHE BOOL "" FORCE)

list(PREPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/modules")
set(CMAKE_PROJECT_gemrb_INCLUDE "${CMAKE_CURRENT_LIST_DIR}/AndroidProjectInclude.cmake")
